name: sample-nodejs
services:
- name: sample-nodejs
  run_command: yarn start
  environment_slug: node-js
  http_port: 8080
  envs:
  - key: SOME_THING
    value: thingy
    scope: RUN_TIME
    type: GENERAL
  - key: ANOTHER_THING
    scope: BUILD_TIME
    type: SECRET
  routes:
  - path: /
