name: sample-nodejs
services:
- build_command: npm run fakeBuildCommand
  run_command: npm run fakeRunCommand
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/sample-nodejs
  name: sample-nodejs
  envs:
  - key: SOME_THING
    value: thingy
    scope: RUN_TIME
    type: GENERAL
  - key: ANOTHER_THING
    scope: BUILD_TIME
    type: SECRET
  routes:
  - path: /
